---

application:
  client-origin-url: ${CLIENT_ORIGIN_URL}

server:
  error:
    whitelabel:
      enabled: false
  port: ${PORT}

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

okta:
  oauth2:
    issuer: ${OKTA_OAUTH2_ISSUER}
    audience: ${OKTA_OAUTH2_AUDIENCE}
...
